# Lab 4: Attribute Transformation an Dimensionality Reduction

## Attribute Transformation

An attribute transform is a function that maps the entire set of values of a given attribute to a new set of replacement values such that each old value can be identified with one of the new values

Dataset contains features with different metrics and scales. For example: "pregnant" and "insulin" values are based on different scales of measurement. The magnitude of "insulin" value is higher than "pregnant" in the diabetes dataset. Hence, many algorithm that are sensitive to varying scales of value will be biased towards the one with higher magnitdue.For example neural netwroks are highly sensitive to scaling of the data attributes. Hence we need to convert the dataset into suitable format before it is fed into the neurons.

#### The solution to varying scale values

We need a mechanism that scales all the attribute values into a given range typically between 0 to +1 or between a certain specified range. This approach is called feature scaling.

Below are two approaches taht converts each feature into same scale

1. Min-Max Scaler (Normalization)
2. Standardization


## Using MinMaxScaler() 

Rescaling X_train dataset

"minj" and "maxj" represent the minimum and maximum values of attribute 'j'. The $j^{th}$ attribute value $x_{i}^{j}$ of the $i^{th}$ row is scaled as:

### $y_{i}^{j} = (x_{i}^{j} - min_{j})/(max_{j}-min_{j})$

We transform only the train dataset for scaling or any data tranformation tasks.

#### Split the cleaned data into input features $(X_{i})$ and output component (Y)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
dbts_new= pd.read_csv('imputed_data_diabetes.csv')
dbts_new.head()

Unnamed: 0  pregnant  glucose    bp       skin  insulin   bmi  pedigree  \
0           0         1     85.0  66.0  29.000000    125.0  26.6     0.351   
1           1         8    183.0  64.0  29.142593    125.0  23.3     0.672   
2           2         1     89.0  66.0  23.000000     94.0  28.1     0.167   
3           3         0    137.0  40.0  35.000000    168.0  43.1     2.288   
4           4         5    116.0  74.0  29.142593    125.0  25.6     0.201   

   age  Diabetic  
0   31         0  
1   32         1  
2   21         0  
3   33         1  
4   30         0

In [3]:
spltd_data = dbts_new.values
# separate the dataset into input and output components
X = spltd_data [:,0:8]
Y = spltd_data[:,8]

#### Separate the splitted dataset into training and testing dataset with training  dataset = 80% of cleaned data and test dataset  = 20% of cleaned dataset

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)

#### Use Sci-Kit learn MinMaxScaler () for normlization

In [5]:
from sklearn.preprocessing import MinMaxScaler
sclr = MinMaxScaler(feature_range=(0, 1))
scaled_data_X_train = sclr.fit_transform(X_train)
# summarize transformed data
np.set_printoptions(precision=4)
print(scaled_data_X_train[0:5,:])

[[0.8629 0.4706 0.7935 0.8367 0.4239 0.2608 0.3967 0.0371]
 [0.8081 0.1176 0.4387 0.6327 0.3804 0.1755 0.4131 0.0717]
 [0.6906 0.1176 0.5032 0.3673 0.1196 0.1106 0.2372 0.2728]
 [0.0875 0.0588 0.329  0.4286 0.0652 0.0288 0.0286 0.1093]
 [0.6488 0.4118 0.9742 0.4694 0.2826 0.1575 0.1411 0.0363]]


#### The above code converted all the feature values into the  scale between 0 and 1 using Normalization or Min-Max scaling.
<font color = green>Some learning algorithms like Neural Networks expect input values between [0,1] hence we use normalization for scaling in such case. </font>

#### Standardization

It is another approach to scaling where the scaled value isn't within the [0,1] range. It is suitable where the data collection process has errors and hence has extreme values or outliers.

The $j^{th}$ attribute value $x_{i}^{j}$ of the ith row is normalized by:

###                         Z-score_normalization (x')=  ($x_{i}^{j}$ -$\mu_{j}$)  /  $\sigma_{j}$

 where the $j^{th}$  attribute has mean $\mu_{j}$ and standard deviation $\sigma_{j}$ .
                       
We use a function "StandardScaler()"  for standardization purpose.

In [6]:
from sklearn.preprocessing import StandardScaler
scale_ftrs_stndrd = StandardScaler().fit(X_train)
scaled_stndrd_X_train = scale_ftrs_stndrd.transform(X_train)
# summarize transformed data
np.set_printoptions(precision=3)
print(scaled_stndrd_X_train[0:5,:])

[[ 1.259  1.257  1.482  2.722  1.852  1.076  0.706 -0.918]
 [ 1.07  -0.542 -0.323  1.104  1.402  0.222  0.82  -0.677]
 [ 0.665 -0.542  0.005 -0.999 -1.302 -0.428 -0.409  0.721]
 [-1.414 -0.842 -0.881 -0.514 -1.866 -1.245 -1.868 -0.416]
 [ 0.521  0.957  2.401 -0.19   0.388  0.042 -1.081 -0.924]]


## Dimensionality Reduction

Dimensionality reduction is all about summarizing the data with most of the information preserved in compact form.Reducing the dimension of the feature space, creates fewer relationships between variables and hence the model is less likely to overfit.

#### One of such technique discussed here is the Principal Component Analysis (PCA)

PCA is a dimensionality-reduction technique for reducing the dimensionality of large data sets, i.e. by transforming a large set of input features into a smaller set which still contains most of the information in the original dataset .But Before applying PCA, the dataset must be rescaled, if not rescaled, the model/algorithm's accuracy may not be improved much.

In [7]:
from sklearn.decomposition import PCA

prcpl_cmpnts = PCA(n_components=3)  # use three diagonal compnents for data reduction and summarization
prncpl_smmry = prcpl_cmpnts.fit(scaled_stndrd_X_train)
print(("Explained Variance: %s") % (prncpl_smmry.explained_variance_ratio_)) # summarize the components


Explained Variance: [0.259 0.159 0.142]


In [8]:
print(prncpl_smmry.components_)

[[ 0.032  0.107  0.445  0.35   0.48   0.337  0.521  0.227]
 [ 0.066  0.495 -0.191  0.493  0.142 -0.471  0.102 -0.467]
 [-0.051  0.512  0.473  0.108 -0.405  0.396 -0.395 -0.153]]



Above code created three principial components as denoted in three separate arrays. Each array represents the component that summarizes the overall data.